### ISSUE TITLE
Some items failing on some country/language codes

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/epub3#25]
Possibly 3-character ISO 639-2 codes are breaking `pycountry/db.py`

````
[ PDT: 2018-06-07 10:14:03 ] Executing: ulimit -v 4194304; PATH=/var/cache/petabox/petabox/sw/bin:$PATH  abbyy2epub  '/var/tmp/autoclean/derive/derrierelepaule0000saga/' 'derrierelepaule0000saga' 'derrierelepaule0000saga' -o '/t/_derrierelepaule0000saga/derrierelepaule0000saga.epub' --tmpdir '/var/tmp/tmp/epub3' 2>&1
Traceback (most recent call last):
  File "/usr/local/bin/abbyy2epub", line 11, in 
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/abbyy_to_epub3/commandline.py", line 95, in main
    epub_outfile=args.out or 'out.epub', tmpdir=args.tmpdir
  File "/usr/local/lib/python3.5/dist-packages/abbyy_to_epub3/create_epub.py", line 1073, in craft_epub
    parser.parse_abbyy()
  File "/usr/local/lib/python3.5/dist-packages/abbyy_to_epub3/parse_abbyy.py", line 271, in parse_abbyy
    self.parse_metadata()
  File "/usr/local/lib/python3.5/dist-packages/abbyy_to_epub3/parse_abbyy.py", line 224, in parse_metadata
    lang = pycountry.languages.get(alpha_3=lang_code)
  File "/usr/local/lib/python3.5/dist-packages/pycountry/db.py", line 45, in load_if_needed
    return f(self, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/pycountry/db.py", line 108, in get
    return self.indices[field][value]
KeyError: 'fre'
```

**Comment by mekarpeles** [comment]
It looks like one can do something like this if we notice the length is not `2`:
```
>>> lang = 'ger'
>>> lang = Country(alpha_3=lang).alpha_2 if len(ger) == 3 else lang
>>> x.alpha_2
'de'
```

**Comment by mekarpeles** [comment]
We may also have to be robust against non-abbreviated languages like `Russian`

**Comment by deborahgu** [comment]
Ah, this wasn't the problem -- we already handled the alternate length case. It turns out we're just not consistent on which iso standard we use.  Luckily `pycountry ` copes well with the situation, and I added a fallback for unknown languages.  I added a robust test set for this as well.

**Comment by mekarpeles** [comment]
We may still be hitting something similar in rare cases:

```
Executing: ulimit -v 4194304; PATH=/var/cache/petabox/petabox/sw/bin:$PATH  abbyy2epub  '/var/tmp/autoclean/derive/chinesecomprehen00poch_460/' 'chinesecomprehen00poch_460' 'chinesecomprehen00poch_460' -o '/t/_chinesecomprehen00poch_460/chinesecomprehen00poch_460.epub' --tmpdir '/var/tmp/tmp/epub3' 2>&1
Traceback (most recent call last):
  File "/usr/local/bin/abbyy2epub", line 11, in 
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/abbyy_to_epub3/commandline.py", line 95, in main
    epub_outfile=args.out or 'out.epub', tmpdir=args.tmpdir
  File "/usr/local/lib/python3.5/dist-packages/abbyy_to_epub3/create_epub.py", line 1073, in craft_epub
    parser.parse_abbyy()
  File "/usr/local/lib/python3.5/dist-packages/abbyy_to_epub3/parse_abbyy.py", line 285, in parse_abbyy
    self.parse_metadata()
  File "/usr/local/lib/python3.5/dist-packages/abbyy_to_epub3/parse_abbyy.py", line 229, in parse_metadata
    self.metadata['language'][0] = lang.alpha_2
  File "/usr/local/lib/python3.5/dist-packages/pycountry/db.py", line 23, in __getattr__
    raise AttributeError
AttributeError
```

Or perhaps this was running using the old code. I can check this item manually and will update this issue.

**Comment by mekarpeles** [comment]
It requires catching AttributeError on `lang.alpha_2`. I'll submit a PR

**Comment by mekarpeles** [comment]
epub3 fails on items with Scribe1-style scandata (inside scandata.zip), which the new epub-generation
https://catalogd.archive.org/log/928860807
