### ISSUE TITLE
epub3 code breaks for old archive.org items

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/epub3#27]
See: https://catalogd.archive.org/log/928860807 ~250 items

Old scribe1-style items store scandata within a scandata.zip, which the new epub-generation script doesn’t know how to find.

**Comment by bfalling** [comment]
@mekarpeles: Is this "just" a matter of having the script try the additional case of the scandata.zip file?

**Comment by mekarpeles** [comment]
@bfalling yes, e.g.:

`https://ia601409.us.archive.org/epub/index.php?id=atlantic07bostuoft&dir=/8/items/atlantic07bostuoft&doc=atlantic07bostuoft&type=epub&debug=1&reCache=true`

This item has no `atlantic07bostuoft_scandata.xml` but instead (a la https://archive.org/download/atlantic07bostuoft) has  `scandata.zip` which contains a `scandata.xml` which can be accessed directly (without unzipping) via `https://archive.org/download/atlantic07bostuoft/scandata.zip/scandata.xml`

So the solution is to either look for `{itemname}_scandata.xml` or `scandata.zip/scandata.xml`

Currently, this is how the error manifests:

```
Traceback (most recent call last):
  File "/usr/local/bin/abbyy2epub", line 11, in 
    load_entry_point('abbyy-to-epub3==1.7.0', 'console_scripts', 'abbyy2epub')()
  File "/usr/local/lib/python3.5/dist-packages/abbyy_to_epub3/commandline.py", line 92, in main
    ace=args.ace,
  File "/usr/local/lib/python3.5/dist-packages/abbyy_to_epub3/create_epub.py", line 179, in __init__
    super(Ebook, self).__init__(item_dir, item_identifier, item_bookpath)
  File "/usr/local/lib/python3.5/dist-packages/abbyy_to_epub3/create_epub.py", line 109, in __init__
    "Invalid path to %s.%s: %s" % (name, ext, dependency)
OSError: Invalid path to scandata.xml: /8/items/atlantic07bostuoft/atlantic07bostuoft_scandata.xml
```
